In [6]:
##given info
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [17]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#to print the data types of both the variables.
#ans1_
list_1=np.asarray(list_)
print("the data type of variable list_1 is", list_1.dtype)
print("the data type of variable array_list is",array_list.dtype)
if list_1.dtype==array_list.dtype:
    print("the datatype of both is the same and it's",list_1.dtype)
else:
    print("the data types of list_1 and array_list are", list_1.dtype, array_list.dtype)

the data type of variable list_1 is <U1
the data type of variable array_list is <U1
the datatype of both is the same and it's <U1


In [30]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and
#array_list.
#ans2
r=0
m=0
#the datatype of every element of the variablr list_1
while r <= (list_1.size - 1):
    print("the data type of ", list_1[r] ,"in the variable list_1 is ", list_1[r].dtype)
    r+=1
#the datatype of every element of the variablr array_list
while m <= (array_list.size - 1):
    print("the data type of ", array_list[m] ,"in the variable array_list is ", array_list[m].dtype)
    m+=1

the data type of  1 in the variable list_1 is  <U1
the data type of  2 in the variable list_1 is  <U1
the data type of  3 in the variable list_1 is  <U1
the data type of  4 in the variable list_1 is  <U1
the data type of  5 in the variable list_1 is  <U1
the data type of  1 in the variable array_list is  <U1
the data type of  2 in the variable array_list is  <U1
the data type of  3 in the variable array_list is  <U1
the data type of  4 in the variable array_list is  <U1
the data type of  5 in the variable array_list is  <U1


In [35]:
#Q3(I). Considering the changes in the variable, array_list Will there be any difference in the data type
#of the elements present in both the variables, list_1 and array_list? If so then print the data types
#of each and every element present in both the variables, list_1 and arra_list.
#ans3
array_list = np.array(object = list_, dtype = int)
if list_1.dtype==array_list.dtype:
    print("the datatype of both the variables list_1 and array_list are the same")
else:
    print("the datatype of the variables list_1 and array_list are ", list_1.dtype, "and",array_list.dtype)
    r=0
    m=0
    #the datatype of every element of the variablr list_1
    while r <= (list_1.size - 1):
        print("the data type of ", list_1[r] ,"in the variable list_1 is ", list_1[r].dtype)
        r+=1
    #the datatype of every element of the variablr array_list
    while m <= (array_list.size - 1):
        print("the data type of ", array_list[m] ,"in the variable array_list is ", array_list[m].dtype)
        m+=1



the datatype of the variables list_1 and array_list are  <U1 and int64
the data type of  1 in the variable list_1 is  <U1
the data type of  2 in the variable list_1 is  <U1
the data type of  3 in the variable list_1 is  <U1
the data type of  4 in the variable list_1 is  <U1
the data type of  5 in the variable list_1 is  <U1
the data type of  1 in the variable array_list is  int64
the data type of  2 in the variable array_list is  int64
the data type of  3 in the variable array_list is  int64
the data type of  4 in the variable array_list is  int64
the data type of  5 in the variable array_list is  int64


In [36]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [37]:
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size
#ans4
#shape of num_array
print("the shape of the variable num_array is ", num_array.shape)
#size of num_array
print("the size of the variable num_array is ", num_array.size)


the shape of the variable num_array is  (2, 3)
the size of the variable num_array is  6


In [43]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#creation function.
#ans5
#creating a 3X3 matrix ore basically an array wich only consists of zero
print("the numpy array of 3*3 matrix containg zeores only \n", np.matrix(np.zeros((3,3))))

the numpy array of 3*3 matrix containg zeores only 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [47]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
#ans6
#creating a 5*5 identity maatrix
print("the 5*5 identity matrix is \n", np.matrix(np.eye(5)),"\n the shape of the identity matrix is \n",np.matrix(np.eye(5)).shape)

the 5*5 identity matrix is 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 
 the shape of the identity matrix is 
 (5, 5)
